---
- name: Install pip modules
  ansible.builtin.pip:
    name: "{{ deps_pip_modules }}"

- name: Wait for collections to be installed
  ansible.builtin.wait_for:
    path: '{{ item | collection_to_path }}'
  loop: '{{ deps_collections }}'
